### ISSUE TITLE
gatheringEverything의 경우 무엇을 모두 합친 것인지 알 수 없는 문제가 있음

### ISSUE THREAD

**Issue by silenc3502** [EDDI-RobotAcademy/lms-frontend#167]
수업에서 사용 했지만 현재 관점에서는 저것이 어떤 Domain 작업인지 파악하는데 어려움이 존재함

**Comment by Meue-L** [comment]
vue <-> fastAPI <-> DLLS 까지의 통신 흐름을 확인하기 위한 도메인이므로, 추후 삭제 예정
